name: Build GWT
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  gradlew-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: |
          chmod +x gradlew
          ./gradlew build
        name: run gradle build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            build/gwt/war/
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/gwt/war/

  deploy_pages:
    needs: gradlew-build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
